# Generated by Django 5.1.5 on 2025-01-25 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Entidades',
                'ordering': ['entidad'],
            },
        ),
        migrations.CreateModel(
            name='DJP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('djp', models.PositiveSmallIntegerField(verbose_name='DJP')),
                ('nombre', models.CharField(max_length=100)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.entidad')),
            ],
            options={
                'verbose_name': 'DJP',
                'verbose_name_plural': 'Distritos Judiciales Penales',
                'ordering': ['entidad', 'djp'],
            },
        ),
        migrations.CreateModel(
            name='DJC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('djc', models.PositiveSmallIntegerField(verbose_name='DJC')),
                ('nombre', models.CharField(max_length=100)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.entidad')),
            ],
            options={
                'verbose_name': 'DJC',
                'verbose_name_plural': 'Distritos Judiciales Civiles',
                'ordering': ['entidad', 'djc'],
            },
        ),
        migrations.CreateModel(
            name='DistritoLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito_local', models.PositiveSmallIntegerField()),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.entidad')),
            ],
            options={
                'verbose_name': 'Distrito Local',
                'verbose_name_plural': 'Distritos Locales',
                'ordering': ['entidad', 'distrito_local'],
            },
        ),
        migrations.CreateModel(
            name='DistritoFederal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito_federal', models.PositiveSmallIntegerField(verbose_name='Distrito')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.entidad')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'ordering': ['entidad', 'distrito_federal'],
            },
        ),
        migrations.CreateModel(
            name='ARE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('are', models.PositiveSmallIntegerField()),
                ('activa', models.BooleanField(default=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('djc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.djc')),
                ('djp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.djp')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.entidad')),
            ],
            options={
                'verbose_name_plural': 'Municipios',
                'ordering': ['entidad', 'municipio'],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.PositiveSmallIntegerField()),
                ('tipo', models.PositiveSmallIntegerField(choices=[(2, 'URBANA'), (3, 'MIXTA'), (4, 'RURAL')])),
                ('pe', models.PositiveIntegerField(blank=True, null=True, verbose_name='PE')),
                ('ln', models.PositiveIntegerField(blank=True, null=True, verbose_name='LN')),
                ('activa', models.BooleanField(default=True)),
                ('are', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gis.are')),
                ('distrito_federal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.distritofederal')),
                ('distrito_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.distritolocal')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.entidad')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.municipio')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['entidad', 'municipio', 'seccion'],
            },
        ),
        migrations.CreateModel(
            name='Padron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pe', models.PositiveIntegerField(verbose_name='PE')),
                ('ln', models.PositiveIntegerField(verbose_name='LN')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.entidad')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.seccion')),
            ],
            options={
                'verbose_name': 'PE y LN',
                'verbose_name_plural': 'PE y LN',
                'ordering': ['entidad', 'seccion'],
            },
        ),
        migrations.CreateModel(
            name='ZORE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zore', models.PositiveSmallIntegerField()),
                ('activa', models.BooleanField(default=True)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.distritofederal')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.entidad')),
            ],
        ),
        migrations.AddField(
            model_name='are',
            name='zore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.zore'),
        ),
    ]
