# Generated by Django 5.1.5 on 2025-01-24 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadisticoseccion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticos', to='gis.seccion'),
        ),
    ]
