# Generated by Django 5.1.5 on 2025-01-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distrito_federal',
            options={'ordering': ['entidad', 'distrito_federal'], 'verbose_name': 'Distrito', 'verbose_name_plural': 'Distritos'},
        ),
        migrations.AlterModelOptions(
            name='distrito_local',
            options={'ordering': ['entidad', 'distrito_local'], 'verbose_name': 'Distrito Local', 'verbose_name_plural': 'Distritos Locales'},
        ),
        migrations.AlterModelOptions(
            name='entidad',
            options={'ordering': ['entidad'], 'verbose_name_plural': 'Entidades'},
        ),
    ]
