# Generated by Django 5.1.5 on 2025-01-24 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0002_alter_estadisticoseccion_seccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadisticoseccion',
            options={'get_latest_by': 'historico'},
        ),
    ]
