# Generated by Django 5.1.5 on 2025-01-23 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0002_alter_distrito_federal_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Distrito_Local',
            new_name='DistritoLocal',
        ),
        migrations.AlterModelOptions(
            name='djc',
            options={'ordering': ['entidad', 'djc'], 'verbose_name': 'DJC', 'verbose_name_plural': 'Distritos Judiciales Civiles'},
        ),
        migrations.AlterModelOptions(
            name='djp',
            options={'ordering': ['entidad', 'djp'], 'verbose_name': 'DJP', 'verbose_name_plural': 'Distritos Judiciales Penales'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ['entidad', 'municipio'], 'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterField(
            model_name='djc',
            name='djc',
            field=models.PositiveSmallIntegerField(verbose_name='DJC'),
        ),
        migrations.AlterField(
            model_name='djp',
            name='djp',
            field=models.PositiveSmallIntegerField(verbose_name='DJP'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='are',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gis.are'),
        ),
        migrations.CreateModel(
            name='DistritoFederal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito_federal', models.PositiveSmallIntegerField(verbose_name='Distrito')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.entidad')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'ordering': ['entidad', 'distrito_federal'],
            },
        ),
        migrations.AlterField(
            model_name='seccion',
            name='distrito_federal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.distritofederal'),
        ),
        migrations.DeleteModel(
            name='Distrito_Federal',
        ),
    ]
