# Generated by Django 5.1.5 on 2025-01-29 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0002_delete_padron'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargosDJP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=150)),
                ('djp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.djp')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.entidad')),
            ],
            options={
                'verbose_name': 'Cargo DJP',
                'verbose_name_plural': 'Cargos DJP',
                'ordering': ['entidad', 'djp', 'cargo'],
            },
        ),
    ]
