# Generated by Django 5.1.5 on 2025-01-24 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0003_alter_estadisticoseccion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadisticoseccion',
            options={'get_latest_by': 'historico__fecha'},
        ),
    ]
