# Generated by Django 5.1.5 on 2025-01-23 21:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0003_rename_distrito_local_distritolocal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('pe', models.PositiveIntegerField(blank=True, null=True)),
                ('ln', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterModelOptions(
            name='seccion',
            options={'ordering': ['entidad', 'municipio', 'seccion'], 'verbose_name': 'Sección', 'verbose_name_plural': 'Secciones'},
        ),
        migrations.AddField(
            model_name='zore',
            name='distrito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gis.distritofederal'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EstadisticoSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.PositiveIntegerField()),
                ('seccion', models.PositiveIntegerField()),
                ('pe', models.PositiveIntegerField()),
                ('ln', models.PositiveIntegerField()),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticos', to='gis.historicope')),
            ],
        ),
    ]
