# Generated by Django 5.1.5 on 2025-01-31 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0003_cargosdjp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargosDJC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=150)),
                ('djc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.djp')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.entidad')),
            ],
            options={
                'verbose_name': 'Cargo DJC',
                'verbose_name_plural': 'Cargos DJC',
                'ordering': ['entidad', 'djc', 'cargo'],
            },
        ),
    ]
